// <auto-generated />
using System;
using FisioScan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FisioScan.Data.Migrations
{
    [DbContext(typeof(FisioScanContext))]
    [Migration("20241230205946_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FisioScan.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            BirthDate = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Dni = "724264567",
                            FirstSurname = "González",
                            Name = "John",
                            SecondSurname = "Rodríguez"
                        },
                        new
                        {
                            PatientId = 2,
                            BirthDate = new DateTime(1995, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            Dni = "723626246",
                            FirstSurname = "Sánchez",
                            Name = "Luis",
                            SecondSurname = "Martínez"
                        },
                        new
                        {
                            PatientId = 3,
                            BirthDate = new DateTime(1974, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            Dni = "745751345",
                            FirstSurname = "Sanz",
                            Name = "Rebeca",
                            SecondSurname = "Gimenez"
                        },
                        new
                        {
                            PatientId = 4,
                            BirthDate = new DateTime(1965, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            Dni = "714265724",
                            FirstSurname = "Prieto",
                            Name = "Javier",
                            SecondSurname = "Alonso"
                        });
                });

            modelBuilder.Entity("FisioScan.Models.Physio", b =>
                {
                    b.Property<int>("PhysioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysioId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Physio");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhysioId");

                    b.ToTable("Physios");

                    b.HasData(
                        new
                        {
                            PhysioId = 1,
                            Email = "admin@admin.com",
                            FirstSurname = "Perez",
                            Name = "Juan",
                            Password = "admin",
                            RegistrationNumber = 1568,
                            Role = "Admin",
                            SecondSurname = "Martínez"
                        },
                        new
                        {
                            PhysioId = 2,
                            Email = "david.calvo@example.com",
                            FirstSurname = "Calvo",
                            Name = "David",
                            Password = "1234",
                            RegistrationNumber = 1247,
                            Role = "Physio",
                            SecondSurname = "Alonso"
                        },
                        new
                        {
                            PhysioId = 3,
                            Email = "rocio.reinosa@example.com",
                            FirstSurname = "Reinosa",
                            Name = "Rocío",
                            Password = "1234",
                            RegistrationNumber = 1174,
                            Role = "Physio",
                            SecondSurname = "Duate"
                        });
                });

            modelBuilder.Entity("FisioScan.Models.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentId"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TreatmentId");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            TreatmentId = 1,
                            CreatedBy = 2,
                            PatientId = 2,
                            TreatmentCause = "lumbalgia",
                            TreatmentDate = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TreatmentId = 2,
                            CreatedBy = 2,
                            PatientId = 2,
                            TreatmentCause = "lumbalgia",
                            TreatmentDate = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TreatmentId = 3,
                            CreatedBy = 3,
                            PatientId = 4,
                            TreatmentCause = "hombro congelado",
                            TreatmentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
