// <auto-generated />
using FisioScan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FisioScan.Data.Migrations
{
    [DbContext(typeof(FisioScanContext))]
    partial class FisioScanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FisioScan.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedBy = 1,
                            Dni = "724264567",
                            FirstSurname = "González",
                            Name = "John",
                            SecondSurname = "Rodríguez"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedBy = 2,
                            Dni = "723626246",
                            FirstSurname = "Sánchez",
                            Name = "Luis",
                            SecondSurname = "Martínez"
                        });
                });

            modelBuilder.Entity("FisioScan.Models.Physio", b =>
                {
                    b.Property<int>("PhysioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysioId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Physio");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhysioId");

                    b.ToTable("Physios");

                    b.HasData(
                        new
                        {
                            PhysioId = 1,
                            Email = "admin@admin.com",
                            FirstSurname = "Perez",
                            Name = "Juan",
                            Password = "admin",
                            RegistrationNumber = 1568,
                            Role = "Admin",
                            SecondSurname = "Martínez"
                        },
                        new
                        {
                            PhysioId = 2,
                            Email = "pakito.perez@example.com",
                            FirstSurname = "Calvo",
                            Name = "David",
                            Password = "1234",
                            RegistrationNumber = 1247,
                            Role = "Physio",
                            SecondSurname = "Alonso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
